import React, { useEffect, useState } from "react";
import { Bell, Plus } from "lucide-react";
import { NotificationItem } from "../types";
interface Props { onShowToast: (msg: string) => void; }
export default function NotificationsView({ onShowToast }: Props) {
 const [items,setItems]=useState<NotificationItem[]>([]); const [form,setForm]=useState({title:'Reminder',message:'',dueAt:''});
 const load=()=>fetch('/api/notifications').then(r=>r.json()).then(setItems); useEffect(()=>{load();},[]);
 const add=async()=>{await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); setForm({title:'Reminder',message:'',dueAt:''}); await load(); onShowToast('Reminder created');};
 const mark=async(id:string,read:boolean)=>{await fetch(`/api/notifications/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({read})}); await load();};
 return <div className="w-full max-w-[900px] mx-auto px-10 py-12"><h2 className="text-[40px] font-black mb-2">Notifications</h2><p className="text-sm text-gray-500 mb-8">Simple local reminder inbox. Browser push/email can be added later.</p><div className="border rounded-xl p-5 mb-6 grid grid-cols-1 md:grid-cols-4 gap-3"><input className="border rounded-lg px-3 py-2 text-sm" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="border rounded-lg px-3 py-2 text-sm md:col-span-2" placeholder="Message" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><div className="flex gap-2"><input className="border rounded-lg px-3 py-2 text-sm flex-1" type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/><button className="bg-[#37352F] text-white px-3 rounded-lg" onClick={add}><Plus className="w-4 h-4"/></button></div></div><div className="space-y-3">{items.map(n=><div key={n.id} className={`border rounded-xl p-4 flex items-start gap-3 ${n.read?'opacity-50':'bg-[#F7F6F3]'}`}><Bell className="w-4 h-4 mt-1"/><div className="flex-1"><div className="font-bold text-sm">{n.title}</div><div className="text-sm text-gray-600">{n.message}</div>{n.dueAt && <div className="text-xs text-gray-400 mt-1">Due: {n.dueAt}</div>}</div><button className="text-xs font-bold underline" onClick={()=>mark(n.id,!n.read)}>{n.read?'Unread':'Read'}</button></div>)}</div></div>;
}
