import React, { useEffect, useState } from "react";
import { User, Bell, Shield, Database, Download, Camera, Check } from "lucide-react";
import { User as UserType } from "../types";

interface SettingsViewProps { currentUser: UserType | null; onUpdateUser: (updatedUser: UserType) => void; onShowToast: (msg: string) => void; }

export default function SettingsView({ currentUser, onUpdateUser, onShowToast }: SettingsViewProps) {
  const [activeTab, setActiveTab] = useState("My Account");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [language, setLanguage] = useState("English (US)"); const [timezone, setTimezone] = useState("Asia/Jakarta"); const [selectedTheme, setSelectedTheme] = useState("Light"); const [avatarUrl, setAvatarUrl] = useState(""); const [role, setRole] = useState("owner");
  useEffect(()=>{ if(currentUser){ setName(currentUser.name); setEmail(currentUser.email); setLanguage(currentUser.language||"English (US)"); setTimezone(currentUser.timezone||"Asia/Jakarta"); setSelectedTheme(currentUser.theme||"Light"); setAvatarUrl(currentUser.avatar||""); setRole(currentUser.role||"owner"); } },[currentUser]);
  const readFile = (file: File) => new Promise<string>((resolve,reject)=>{const r=new FileReader(); r.onload=()=>resolve(String(r.result)); r.onerror=reject; r.readAsDataURL(file);});
  const save = async()=>{ if(!currentUser)return; const updated={...currentUser,name,email,language,timezone,theme:selectedTheme,avatar:avatarUrl,role}; const res=await fetch('/api/user',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(updated)}); const data=await res.json(); onUpdateUser(data); document.documentElement.dataset.theme=selectedTheme.toLowerCase(); onShowToast('Settings saved'); };
  const exportData=async()=>{ const [pages,tasks,assets,fitness,habits]=await Promise.all([fetch('/api/pages').then(r=>r.json()),fetch('/api/tasks').then(r=>r.json()),fetch('/api/assets').then(r=>r.json()),fetch('/api/fitness').then(r=>r.json()),fetch('/api/habits').then(r=>r.json())]); const blob=new Blob([JSON.stringify({pages,tasks,assets,fitness,habits},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='personal-workspace-export.json'; a.click(); onShowToast('Workspace exported as JSON'); };
  const nav=[['My Account',<User className="w-4 h-4"/>],['Notifications',<Bell className="w-4 h-4"/>],['Security',<Shield className="w-4 h-4"/>],['Workspace',<Database className="w-4 h-4"/>],['Import & Export',<Download className="w-4 h-4"/>]] as const;
  return <div className="w-full max-w-[1000px] mx-auto px-10 py-12"><h2 className="text-[40px] font-bold text-black mb-10">Settings</h2><div className="flex gap-10 items-start"><aside className="w-52 flex-shrink-0 space-y-1">{nav.map(([n,i])=><button key={n} onClick={()=>setActiveTab(n)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm ${activeTab===n?'bg-[#e7e2d9] text-black font-semibold':'text-gray-500 hover:bg-gray-100'}`}>{i}<span>{n}</span></button>)}</aside><main className="flex-1 max-w-[680px]">
    {activeTab==='My Account' && <div className="space-y-8"><section className="border rounded-xl p-6"><h3 className="font-bold mb-5">Profile</h3><div className="flex items-center gap-5 mb-6"><label className="relative cursor-pointer"><img src={avatarUrl || 'https://placehold.co/160x160?text=PW'} className="w-20 h-20 rounded-full object-cover border"/><span className="absolute bottom-0 right-0 bg-black text-white p-1.5 rounded-full"><Camera className="w-3 h-3"/></span><input type="file" accept="image/*" className="hidden" onChange={async e=>{const f=e.target.files?.[0]; if(f) setAvatarUrl(await readFile(f));}}/></label><div><div className="font-semibold">Profile Picture</div><p className="text-xs text-gray-500">Click avatar to upload local JPG/PNG. It is saved in database as data URL.</p><button className="text-xs underline mt-2" onClick={()=>setAvatarUrl('')}>Remove photo</button></div></div><label className="block text-xs font-bold uppercase text-gray-400 mb-1">Display Name</label><input className="w-full border rounded-lg px-3 py-2 mb-3" value={name} onChange={e=>setName(e.target.value)}/><label className="block text-xs font-bold uppercase text-gray-400 mb-1">Email</label><input className="w-full border rounded-lg px-3 py-2" value={email} onChange={e=>setEmail(e.target.value)}/></section><section className="border rounded-xl p-6"><h3 className="font-bold mb-5">Theme & Region</h3><div className="grid grid-cols-2 gap-3 mb-5"><select className="border rounded-lg px-3 py-2" value={language} onChange={e=>setLanguage(e.target.value)}><option>English (US)</option><option>Indonesian</option><option>Japanese</option></select><select className="border rounded-lg px-3 py-2" value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Asia/Jakarta</option><option>UTC</option><option>America/Los_Angeles</option></select></div><div className="flex gap-3">{['Light','Dark','System'].map(t=><button key={t} onClick={()=>setSelectedTheme(t)} className={`px-4 py-3 rounded-xl border ${selectedTheme===t?'border-black font-bold':'border-gray-200'}`}>{selectedTheme===t && <Check className="inline w-3 h-3 mr-1"/>}{t}</button>)}</div></section><div className="flex justify-end"><button className="bg-black text-white px-7 py-2 rounded-lg" onClick={save}>Save Changes</button></div></div>}
    {activeTab==='Notifications' && <div className="border rounded-xl p-6"><h3 className="font-bold mb-2">Notification Settings</h3><p className="text-sm text-gray-500 mb-4">Use the Notifications page to create reminders. This setting panel documents notification behavior.</p><button className="bg-black text-white rounded-lg px-4 py-2" onClick={()=>onShowToast('Reminder center is available from the sidebar')}>Test Notification Toast</button></div>}
    {activeTab==='Security' && <div className="border rounded-xl p-6"><h3 className="font-bold mb-2">Security & Role</h3><p className="text-sm text-gray-500 mb-4">Current local role controls future permission logic.</p><select value={role} onChange={e=>setRole(e.target.value)} className="border rounded-lg px-3 py-2"><option>owner</option><option>admin</option><option>member</option><option>viewer</option></select><button className="ml-3 bg-black text-white rounded-lg px-4 py-2" onClick={save}>Save Role</button></div>}
    {activeTab==='Workspace' && <div className="border rounded-xl p-6"><h3 className="font-bold mb-2">Workspace</h3><p className="text-sm text-gray-500">Workspace uses SQLite for local development. For production/multi-user, switch DATABASE_URL to PostgreSQL and run Prisma migration.</p><div className="mt-4 text-xs bg-[#F7F6F3] border rounded-lg p-3">Online status is updated every 30 seconds via /api/user/online.</div></div>}
    {activeTab==='Import & Export' && <div className="border rounded-xl p-6"><h3 className="font-bold mb-2">Import & Export</h3><p className="text-sm text-gray-500 mb-4">Export pages, tasks, assets, fitness, and habit data as JSON.</p><button onClick={exportData} className="bg-black text-white rounded-lg px-4 py-2">Export Workspace JSON</button><p className="text-xs text-gray-400 mt-3">Import is intentionally not auto-applied yet to avoid overwriting your database accidentally.</p></div>}
  </main></div></div>;
}
